-- =====================================================
-- INSERT 10 Headteacher Portal User Manuals
-- Run this in your Supabase SQL Editor
-- Clean plain text content, no markdown symbols
-- =====================================================

-- Post 1: How to Set Up School Profile and Branding
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Set Up School Profile and Branding',
  'how-to-set-up-school-profile-and-branding',
  'Administration',
  'Headteacher',
  'Admin Guide',
  '4 min read',
  'Labour Edu Support Team',
  'Learn how to configure your school name, motto, address, contact details, and upload your official school crest or logo in the Settings panel.',
  $BODY$How to Set Up School Profile and Branding

Follow these steps to configure your school identity on the platform:

Step 1. Log in with your Headteacher or Admin credentials.

Step 2. Click on Settings on the left menu.

Step 3. Under School Details, enter the following:
  - School Name
  - Motto
  - Address
  - Circuit
  - District
  - Region
  - School contact phone numbers and email address

Step 4. Under School Crest or Logo, click Upload Logo and select your school emblem (PNG or JPEG).

Step 5. Click Save Settings.

Your school profile and branding will now appear on all report cards and official documents generated by the system.$BODY$,
  true,
  '2026-08-18'
);

-- Post 2: How to Set Up Digital Signature for Report Cards
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Set Up Digital Signature for Report Cards',
  'how-to-set-up-digital-signature-for-report-cards',
  'Administration',
  'Headteacher',
  'Admin Guide',
  '3 min read',
  'Labour Edu Support Team',
  'Set up your official headteacher signature to appear automatically on all generated student report cards, either by drawing it on screen or uploading a scanned image.',
  $BODY$How to Set Up Digital Signature for Report Cards

Your signature will print automatically on every student report card once configured.

Step 1. Go to Settings, then Headteacher Signature.

Step 2. Choose one of two options:

  Option A - Draw Signature: Use your mouse or phone/tablet touch screen to draw your signature in the signature box.

  Option B - Upload Image: Click Upload Signature File to upload a scanned image of your official signature.

Step 3. Click Save Signature.

Your signature will now print automatically on all generated student report cards.$BODY$,
  true,
  '2026-08-18'
);

-- Post 3: How to Set the Active Academic Term and Vacation Dates
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Set the Active Academic Term and Vacation Dates',
  'how-to-set-active-academic-term-and-vacation-dates',
  'Administration',
  'Headteacher',
  'Admin Guide',
  '3 min read',
  'Labour Edu Support Team',
  'Configure the current academic year, active term, vacation closing date, and next term reopening date so they appear correctly on all terminal reports.',
  $BODY$How to Set the Active Academic Term and Vacation Dates

Keep your academic calendar up to date so reports reflect the correct term and dates.

Step 1. Go to Settings, then Academic Session.

Step 2. Select the Current Academic Year (e.g. 2025/2026).

Step 3. Select the Current Term (e.g. Term 1, Term 2, or Term 3).

Step 4. Enter the Vacation Date (closing date for this term).

Step 5. Enter the Next Term Begins Date (reopening date).

Step 6. Click Save Changes.

These dates will automatically appear on all terminal reports generated for the selected term.$BODY$,
  true,
  '2026-08-18'
);

-- Post 4: How to Configure Grading Scale and Assessment Weights
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Configure Grading Scale and Assessment Weights',
  'how-to-configure-grading-scale-and-assessment-weights',
  'Academics',
  'Headteacher',
  'Admin Guide',
  '4 min read',
  'Labour Edu Support Team',
  'Define how continuous assessment and exam scores are weighted, set CA component breakdowns, and customize the grading scale with letter grades and auto-remarks.',
  $BODY$How to Configure Grading Scale and Assessment Weights

Customize how student scores are calculated, weighted, and graded.

Step 1. Navigate to Settings, then Assessment and Grading.

Step 2. Set your Assessment Weight Ratio:
  - Continuous Assessment (CA) percentage (e.g. 30% or 50%)
  - Exam Score percentage (e.g. 70% or 50%)

Step 3. Set your CA Components:
  - Class Tests max score
  - Group Work max score
  - Project Work max score

Step 4. Review or customize the Grading Scale:
  - Grade boundaries
  - Letter grades
  - Auto-remarks

Step 5. Click Save Grading Settings.

All scores entered by teachers will now be calculated and graded according to your configured weights and scale.$BODY$,
  true,
  '2026-08-18'
);

-- Post 5: How to Add Teachers and Assign Classes/Subjects
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Add Teachers and Assign Classes/Subjects',
  'how-to-add-teachers-and-assign-classes-subjects',
  'Administration',
  'Headteacher',
  'Admin Guide',
  '5 min read',
  'Labour Edu Support Team',
  'Step-by-step guide to creating teacher accounts, assigning them to classes and subjects, and designating class teachers for each class.',
  $BODY$How to Add Teachers and Assign Classes/Subjects

Register your teaching staff and link them to the correct classes and subjects.


Part A - Creating a Teacher Account

Step 1. Go to Teachers or Staff on the left menu.

Step 2. Click the Add New Teacher button.

Step 3. Fill in the following details:
  - Full Name
  - Staff ID (e.g. STF-001)
  - Email Address
  - Assigned Role (Teacher, Class Teacher, or Admin)

Step 4. Click Create Teacher Account.


Part B - Assigning Classes and Subjects

Step 5. Go to Teaching Assignments (or Class Setup).

Step 6. Choose the Class and Subject, then select the teacher from the dropdown.

Step 7. Set the Class Teacher (Form Master) for each class.

Step 8. Click Save Assignments.

Teachers will now be able to log in and enter scores for their assigned classes and subjects.$BODY$,
  true,
  '2026-08-18'
);

-- Post 6: How to Add Learners (Students)
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Add Learners (Students)',
  'how-to-add-learners-students',
  'Administration',
  'Headteacher',
  'Admin Guide',
  '5 min read',
  'Labour Edu Support Team',
  'Two methods to register students: add them one by one through the form, or bulk upload an entire class roster using the Excel/CSV import template.',
  $BODY$How to Add Learners (Students)

You can register students individually or upload an entire roster at once.


Option A - Adding Students Individually

Step 1. Go to Learners Directory.

Step 2. Click Add Learner.

Step 3. Enter the student details:
  - Full Name
  - Gender
  - Date of Birth
  - Class
  - Guardian Contact

Step 4. Click Save Learner.


Option B - Bulk Uploading Students via Excel or CSV

Step 1. Go to Learners Directory.

Step 2. Click Import Learners (CSV/Excel).

Step 3. Click Download Template to get the sample spreadsheet.

Step 4. Open the template on your computer, paste your student roster, and save it.

Step 5. Click Choose File, select your spreadsheet, and click Upload and Import.

All imported students will appear in the Learners Directory under their assigned class.$BODY$,
  true,
  '2026-08-18'
);

-- Post 7: How to Top Up the School Wallet
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Top Up the School Wallet',
  'how-to-top-up-the-school-wallet',
  'Billing & Subscriptions',
  'Headteacher',
  'Billing Guide',
  '3 min read',
  'Labour Edu Support Team',
  'Fund your school wallet via Mobile Money (MTN, Telecel, AT) or Bank Card (Visa/Mastercard) through the secure Paystack payment gateway.',
  $BODY$How to Top Up the School Wallet

Add funds to your school wallet to pay for term subscriptions and unlock report card generation.

Step 1. Go to School Wallet (or Financials) on the left menu.

Step 2. Look at the Wallet Balance card and click Top Up Wallet.

Step 3. Enter the amount in Ghana Cedis you wish to deposit (e.g. 500).

Step 4. Select your payment method on the Paystack popup:

  Mobile Money - MTN, Telecel, or AT Money. Enter your phone number and approve the prompt on your phone.

  Bank Card - Visa or Mastercard. Enter your card details and complete the transaction.

Step 5. Once payment is completed, your wallet balance will update immediately.

Funds are available instantly after a successful payment. You can now use your wallet balance to settle term subscription bills.$BODY$,
  true,
  '2026-08-18'
);

-- Post 8: How to Approve and Settle a Term Subscription Bill
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Approve and Settle a Term Subscription Bill',
  'how-to-approve-and-settle-term-subscription-bill',
  'Billing & Subscriptions',
  'Headteacher',
  'Billing Guide',
  '4 min read',
  'Labour Edu Support Team',
  'Understand your term bill calculation (learner count x rate), check if your school qualifies for the free first term, and approve payment from your wallet to unlock reports.',
  $BODY$How to Approve and Settle a Term Subscription Bill

Pay your term fee to unlock full report card generation for the active term.

Step 1. Go to School Wallet (or Financials) on the left menu.

Step 2. Locate the Active Term Bill card. It shows:
  - Active Learner Count
  - Rate per Learner
  - Total Due

Step 3. Check your bill status:

  If your school is on its First Term Free Trial, the bill will display GHS 0.00 (Waived - Free First Term).

  If on a paid term, ensure your wallet balance is sufficient for the amount due.

Step 4. Click the blue button: Approve and Pay Term Bill.

Step 5. The fee will be deducted automatically from your wallet.

Your report card generation will be fully unlocked for the active term once the bill is settled.$BODY$,
  true,
  '2026-08-18'
);

-- Post 9: How to Generate, Print, and Download Report Cards
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Generate, Print, and Download Report Cards',
  'how-to-generate-print-and-download-report-cards',
  'Academics',
  'Headteacher',
  'Admin Guide',
  '5 min read',
  'Labour Edu Support Team',
  'Generate terminal report cards for an entire class, download them as a batch PDF, print individual student reports, and toggle between full color and black-and-white print modes.',
  $BODY$How to Generate, Print, and Download Report Cards

Compile and output professional terminal report cards for your students.

Step 1. On the left navigation menu, click on Academic Reports (or Reports).

Step 2. Select the following:
  - Academic Year
  - Term
  - Class

Step 3. Click Generate All Reports to compile all terminal scores, grades, positions, attendance, and remarks.

Step 4. Choose your preferred output:

  Print Batch or Download All (PDF) - Downloads all student report cards in that class in one complete document ready for printing.

  Print Individual - Click the Print button next to a specific student name to output only their report card.

  Color Mode - Toggle between Full Color design or Black and White printer-friendly mode.

Report cards include all scores, grades, class positions, attendance records, teacher remarks, headteacher remarks, and your digital signature.$BODY$,
  true,
  '2026-08-18'
);

-- Post 10: How to Release Report Cards to the Parent Portal
INSERT INTO blog_posts (title, slug, category, target_role, featured_badge, read_time, author, summary, content, is_published, date)
VALUES (
  'How to Release Report Cards to the Parent Portal',
  'how-to-release-report-cards-to-parent-portal',
  'Academics',
  'Headteacher',
  'Admin Guide',
  '3 min read',
  'Labour Edu Support Team',
  'Publish completed terminal reports online so parents can access, view, and download their child report card directly from the Parent Portal on their smartphones.',
  $BODY$How to Release Report Cards to the Parent Portal

Make terminal reports available online for parents to view and download.

Step 1. Navigate to Academic Reports, then Parent Portal Release.

Step 2. Select the Class and Term.

Step 3. Toggle the switch: Release Reports Online for this Term to ON (Green).

Step 4. Click Publish Reports.

Parents can now visit the school Parent Portal and enter their child Student ID to view and download terminal reports directly from their smartphones.$BODY$,
  true,
  '2026-08-18'
);
